.PHONY: help install dev run test migrate migration docker-up docker-down clean

# Default target when invoking `make`
help: ## Display available commands
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

install: ## Install dependencies using uv
	uv sync

dev: ## Run the development server with reload enabled
	uv run uvicorn app.main:app --port 8000 --reload

run: dev ## Alias for `make dev`

test: ## Run the test suite with pytest
	uv run pytest -v

migrate: ## Run Alembic database migrations (`alembic upgrade head`)
	uv run alembic upgrade head

migration: ## Generate a new autogenerated Alembic migration (`make migration m="description"`)
	@if [ -z "$(m)" ]; then echo "Error: Please provide a migration message using m=\"your message\""; exit 1; fi
	uv run alembic revision --autogenerate -m "$(m)"

docker-up: ## Start local ZooKeeper and Redis services in the background using Docker Compose
	docker compose up -d

docker-down: ## Stop and remove local Docker Compose services
	docker compose down

clean: ## Clean up cache directories (`__pycache__`, `.pytest_cache`, etc.)
	find . -type d -name "__pycache__" -exec rm -rf {} +
	find . -type f -name "*.pyc" -delete
	rm -rf .pytest_cache
